{{- if .Values.wazuhManager.worker.enabled }}
apiVersion: {{ include "wazuh.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-worker
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    app: wazuh-manager
    node-type: worker
spec:
  replicas: {{ .Values.wazuhManager.worker.replicaCount }}
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: worker
  serviceName: {{ include "wazuh.fullname" . }}-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: worker
        {{- include "wazuh.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wazuh.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.wazuhManager.worker.securityContext.fsGroup }}
      {{- if eq .Values.wazuhManager.worker.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: wazuh-manager
                  node-type: worker
      {{- else if eq .Values.wazuhManager.worker.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: wazuh-manager
                    node-type: worker
      {{- end }}
      volumes:
        {{- if .Values.certificates.enabled }}
        - name: wazuh-server-certs
          secret:
            secretName: {{ include "wazuh.fullname" . }}-indexer-admin-certs
        {{- end }}
        - name: filebeat-config
          configMap:
            name: {{ include "wazuh.fullname" . }}-filebeat-config
      containers:
        - name: wazuh-manager
          image: "{{ .Values.wazuhManager.worker.image.repository }}:{{ .Values.wazuhManager.worker.image.tag }}"
          imagePullPolicy: {{ .Values.wazuhManager.worker.image.pullPolicy }}
          resources:
            {{- toYaml .Values.wazuhManager.worker.resources | nindent 12 }}
          securityContext:
            capabilities:
              add: {{ .Values.wazuhManager.worker.securityContext.capabilities.add }}
          env:
            - name: GLIBC_TUNABLES
              value: "glibc.pthread.rseq=0"
          ports:
            - containerPort: 1514
              name: agents-events
            - containerPort: 1516
              name: cluster
          volumeMounts:
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/api/configuration
              subPath: wazuh/var/ossec/api/configuration
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/etc
              subPath: wazuh/var/ossec/etc
            {{- if .Values.certificates.enabled }}
            - name: wazuh-server-certs
              mountPath: /var/ossec/etc/certs/root-ca.pem
              readOnly: true
              subPath: root-ca.pem
            - name: wazuh-server-certs
              mountPath: /var/ossec/etc/certs/server.pem
              subPath: server.pem
              readOnly: true
            - name: wazuh-server-certs
              mountPath: /var/ossec/etc/certs/server-key.pem
              subPath: server-key.pem
              readOnly: true
            {{- end }}
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/logs
              subPath: wazuh/var/ossec/logs
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/queue
              subPath: wazuh/var/ossec/queue
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/var/multigroups
              subPath: wazuh/var/ossec/var/multigroups
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/integrations
              subPath: wazuh/var/ossec/integrations
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/active-response/bin
              subPath: wazuh/var/ossec/active-response/bin
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/agentless
              subPath: wazuh/var/ossec/agentless
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/ossec/wodles
              subPath: wazuh/var/ossec/wodles
            - name: filebeat-config
              mountPath: /etc/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
            - name: {{ include "wazuh.fullname" . }}-manager-worker
              mountPath: /var/lib/filebeat
              subPath: filebeat/var/lib/filebeat
      {{- with .Values.wazuhManager.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wazuhManager.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.wazuhManager.worker.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "wazuh.fullname" . }}-manager-worker
      spec:
        accessModes: {{ .Values.wazuhManager.worker.persistence.accessModes }}
        {{- if .Values.wazuhManager.worker.persistence.storageClass }}
        storageClassName: {{ .Values.wazuhManager.worker.persistence.storageClass }}
        {{- else if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.wazuhManager.worker.persistence.size }}
  {{- end }}
{{- end }}