apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-authd-pass
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
type: Opaque
data:
  authd.pass: {{ .Values.secrets.authdPass | b64enc | quote }}