apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-wazuh-api-cred
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.wazuhApi.username | b64enc | quote }}
  password: {{ .Values.secrets.wazuhApi.password | b64enc | quote }}