apiVersion: {{ include "wazuh.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    app: wazuh-indexer
spec:
  serviceName: {{ include "wazuh.fullname" . }}-indexer
  replicas: {{ .Values.wazuhIndexer.replicaCount }}
  selector:
    matchLabels:
      app: wazuh-indexer
  template:
    metadata:
      labels:
        app: wazuh-indexer
        {{- include "wazuh.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wazuh.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.wazuhIndexer.securityContext.fsGroup }}
      initContainers:
        - name: volume-mount-hack
          image: busybox:latest
          command:
            - sh
            - -c
            - chown -R 1000:1000 /var/lib/wazuh-indexer
          volumeMounts:
            - name: {{ include "wazuh.fullname" . }}-indexer
              mountPath: /var/lib/wazuh-indexer
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
        - name: increase-the-vm-max-map-count
          image: busybox:latest
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: {{ .Values.wazuhIndexer.securityContext.privileged }}
        - name: fix-cert-permissions
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              cp /tmp-certs-node/tls.crt /certs/node.pem
              cp /tmp-certs-node/tls.key /certs/node-key.pem
              cp /tmp-certs-ca/ca.crt /certs/root-ca.pem
              cp /tmp-certs-admin/tls.crt /certs/admin.pem
              cp /tmp-certs-admin/tls.key /certs/admin-key.pem
              chmod 644 /certs/*.pem
              chown -R 1000:1000 /certs
          volumeMounts:
            - name: indexer-certs
              mountPath: /tmp-certs-node
            - name: admin-certs
              mountPath: /tmp-certs-admin
            - name: ca-cert
              mountPath: /tmp-certs-ca
            - name: certs-volume
              mountPath: /certs
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: indexer-config
          configMap:
            name: {{ include "wazuh.fullname" . }}-indexer-config
        - name: indexer-certs
          secret:
            secretName: {{ include "wazuh.fullname" . }}-indexer-node-certs
        - name: admin-certs
          secret:
            secretName: {{ include "wazuh.fullname" . }}-indexer-admin-certs
        - name: ca-cert
          secret:
            secretName: {{ include "wazuh.fullname" . }}-ca-secret
        - name: certs-volume
          emptyDir: {}
      containers:
        - name: wazuh-indexer
          image: "{{ .Values.wazuhIndexer.image.repository }}:{{ .Values.wazuhIndexer.image.tag }}"
          imagePullPolicy: {{ .Values.wazuhIndexer.image.pullPolicy }}
          resources:
            {{- toYaml .Values.wazuhIndexer.resources | nindent 12 }}
          ports:
            - containerPort: 9200
              name: indexer-rest
            - containerPort: 9300
              name: indexer-nodes
          env:
            - name: bootstrap.memory_lock
              value: "false"
            - name: network.host
              value: "0.0.0.0"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.initial_cluster_manager_nodes
              value: {{ .Values.wazuhIndexer.cluster.initialClusterManagerNodes | quote }}
            - name: discovery.seed_hosts
              value: {{ .Values.wazuhIndexer.cluster.seedHosts | quote }}
            - name: node.max_local_storage_nodes
              value: {{ .Values.wazuhIndexer.cluster.maxLocalStorageNodes | quote }}
            - name: OPENSEARCH_JAVA_OPTS
              value: {{ .Values.wazuhIndexer.javaOpts | quote }}
            - name: OPENSEARCH_PATH_CONF
              value: "/usr/share/wazuh-indexer/config"
            - name: DISCOVERY_SERVICE
              value: {{ include "wazuh.fullname" . }}-indexer
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wazuh.fullname" . }}-indexer-cred
                  key: username
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wazuh.fullname" . }}-indexer-cred
                  key: password
          volumeMounts:
            - name: indexer-config
              mountPath: /usr/share/wazuh-indexer/config
              readOnly: true
            - name: certs-volume
              mountPath: /usr/share/wazuh-indexer/certs
              readOnly: true
            - name: {{ include "wazuh.fullname" . }}-indexer
              mountPath: /var/lib/wazuh-indexer
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      {{- with .Values.wazuhIndexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wazuhIndexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wazuhIndexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "wazuh.fullname" . }}-indexer
      spec:
        accessModes: {{ .Values.wazuhIndexer.persistence.accessModes }}
        {{- if .Values.wazuhIndexer.persistence.storageClass }}
        {{- if (eq "-" .Values.wazuhIndexer.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.wazuhIndexer.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.wazuhIndexer.persistence.size | quote }}