{{- if and .Values.networkPolicies.enabled .Values.wazuhIndexer.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: wazuh-indexer
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: wazuh-dashboard
      ports:
        - protocol: TCP
          port: 9200
    - from:
        - podSelector:
            matchLabels:
              app: wazuh-manager
              node-type: master
      ports:
        - protocol: TCP
          port: 9200
    - from:
        - podSelector:
            matchLabels:
              app: wazuh-indexer
      ports:
        - protocol: TCP
          port: 9300
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer-egress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: wazuh-indexer
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: wazuh-indexer
      ports:
        - protocol: TCP
          port: 9300
    - to:
        - podSelector:
            matchLabels:
              app: wazuh-indexer
      ports:
        - protocol: TCP
          port: 9200
{{- end }}